### ISSUE TITLE
Tucson 2021

### ISSUE THREAD

**Issue by tibi03** [greenluigi1/HyundaiFirmwareDecrypter#1]
hello, it should work for any model? i tend to try it on a Tucosn nx4 with 8" display.

**Comment by greenluigi1** [comment]
The firmware decrypter tool will only work if your model has a Display Audio Gen2V head unit.

To see if your head unit uses Display Audio Gen2V, go [here](https://update.hyundai.com/US/EN/updateNoticeView/983) and check if your head unit's menus looks like the ones below the Display Audio Gen2V button.

If you head unit looks like Display Audio Gen1, then your head unit is not compatible with this tool.

**Comment by tibi03** [comment]
Thanks, yes its Display Audio Gen2V.
