### ISSUE TITLE
How about October 2023 version?

### ISSUE THREAD

**Issue by tkalfaoglu** [greenluigi1/HyundaiFirmwareDecrypter#3]
Great work! Thank you very much, I read your deciphering of the Hyundai code.
I tried to do the same with the October 2023, but the update file is now called
upgrade.lgk and it doesn't seem to be a zip file anymore.
Mine is  CAVNEU_H,  2017 ioniq btw.

I need to get into the engineering mode actually to set the location of the car (the GPS is not working due to my Factory Reset blunder). However, they seem to have changed the code from 7,5,3 to something else, because although I can get into the dealer mode with the 7,3,1 volume, the 7,5,3 does not work.
Any ideas? Many thanks!

**Comment by greenluigi1** [comment]
This tool is for the D-AUDIO 2V head units which use [this](https://update.hyundai.com/US/EN/updateNoticePopup1/983) firmware which was last updated 14 April 2023.

I believe the non-navigation 2017 Ioniq uses a D-AUDIO 1 head unit and the navigation version uses the Gen5 Wide head unit, both of which are not compatible with this tool and would require different tools and methods for modification.

Also, the method of modification might change depending on the region of the head unit. The methods used to modify a North American or Korean unit might be different compared to a European or Middle Eastern unit.

**Comment by tkalfaoglu** [comment]
Many thanks.  My EU version is with navigation and is the compact Gen5 model.
They combined the maps and system update into one huge SD-Card now. The updater recommends a 32GB card.
